/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Context, ContextInterface } from "../Context";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x40fefe02",
        type: "bytes32",
      },
    ],
    name: "c_0x40fefe02",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

export class Context__factory {
  static readonly abi = _abi;
  static createInterface(): ContextInterface {
    return new utils.Interface(_abi) as ContextInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Context {
    return new Contract(address, _abi, signerOrProvider) as Context;
  }
}
