/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOPAgreement, IOPAgreementInterface } from "../IOPAgreement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "remainingBalance",
        type: "uint256",
      },
    ],
    name: "validateAgreement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOPAgreement__factory {
  static readonly abi = _abi;
  static createInterface(): IOPAgreementInterface {
    return new utils.Interface(_abi) as IOPAgreementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOPAgreement {
    return new Contract(address, _abi, signerOrProvider) as IOPAgreement;
  }
}
