/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PairHelper, PairHelperInterface } from "../PairHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x4d2ab037",
        type: "bytes32",
      },
    ],
    name: "c_0x4d2ab037",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60a3610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80635b4f6f22146038575b600080fd5b604e6004803603810190604a91906053565b6050565b005b50565b6000602082840312156063578081fd5b813590509291505056fea264697066735822122046ac0011ea3073178b9a20fc48d68b9848a8bbb87374ff89fe3fcccc8844cae464736f6c63430008040033";

type PairHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PairHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PairHelper__factory extends ContractFactory {
  constructor(...args: PairHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "PairHelper";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PairHelper> {
    return super.deploy(overrides || {}) as Promise<PairHelper>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PairHelper {
    return super.attach(address) as PairHelper;
  }
  connect(signer: Signer): PairHelper__factory {
    return super.connect(signer) as PairHelper__factory;
  }
  static readonly contractName: "PairHelper";
  public readonly contractName: "PairHelper";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PairHelperInterface {
    return new utils.Interface(_abi) as PairHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PairHelper {
    return new Contract(address, _abi, signerOrProvider) as PairHelper;
  }
}
